on:
  [ push, pull_request ]

name: Build & Test

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test
        run: ./gradlew clean build test
      - name: Publish coverage report
        if: ${{ github.event_name == 'pull_request' }}
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/jacoco/test.exec
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 60